# Imputing Missing Data

Removing observations with missing data

Performing mean or median imputation

Implementing mode or frequent category imputation

Replacing missing values with an arbitrary number

Capturing missing values in a bespoke category

Replacing missing values with a value at the end of the distribution

Implementing random sample imputation

Adding a missing value indicator variable

Performing multivariate imputation by chained equations

Assembling an imputation pipeline with scikit-learn

Assembling an imputation pipeline with Feature-engine

In [19]:
import random
import pandas as pd
import numpy as np

In [22]:
data = pd.read_csv('D:/FSDS-iNeuron/3.Resource/Dataset/crx.data', header=None)

In [24]:
varnames = ['A'+str(s) for s in range(1,17)]

In [27]:
data.columns = varnames

In [28]:
data.head()

A1     A2     A3 A4 A5 A6 A7    A8 A9 A10  A11 A12 A13    A14  A15 A16
0  b  30.83  0.000  u  g  w  v  1.25  t   t    1   f   g  00202    0   +
1  a  58.67  4.460  u  g  q  h  3.04  t   t    6   f   g  00043  560   +
2  a  24.50  0.500  u  g  q  h  1.50  t   f    0   f   g  00280  824   +
3  b  27.83  1.540  u  g  w  v  3.75  t   t    5   t   g  00100    3   +
4  b  20.17  5.625  u  g  w  v  1.71  t   f    0   f   s  00120    0   +

Seprating Categorical and Numerical Columns
Categorical:

    - Nominal  (Categorical/No numerical value)
        - gender
        - race/ethnicity
        - lunch
        - test preparation course
    - Odinal  (Order mtters but value doesn't)
        - parental level of education
Numerical:

    - Continuous
        - math score
        - reading score
        - writing score
    - Discrete
        - No column

In [30]:
data['A1'].unique()

array(['b', 'a', '?'], dtype=object)

In [31]:
data['A2'].unique()

array(['30.83', '58.67', '24.50', '27.83', '20.17', '32.08', '33.17',
       '22.92', '54.42', '42.50', '22.08', '29.92', '38.25', '48.08',
       '45.83', '36.67', '28.25', '23.25', '21.83', '19.17', '25.00',
       '47.75', '27.42', '41.17', '15.83', '47.00', '56.58', '57.42',
       '42.08', '29.25', '42.00', '49.50', '36.75', '22.58', '27.25',
       '23.00', '27.75', '54.58', '34.17', '28.92', '29.67', '39.58',
       '56.42', '54.33', '41.00', '31.92', '41.50', '23.92', '25.75',
       '26.00', '37.42', '34.92', '34.25', '23.33', '23.17', '44.33',
       '35.17', '43.25', '56.75', '31.67', '23.42', '20.42', '26.67',
       '36.00', '25.50', '19.42', '32.33', '34.83', '38.58', '44.25',
       '44.83', '20.67', '34.08', '21.67', '21.50', '49.58', '27.67',
       '39.83', '?', '37.17', '25.67', '34.00', '49.00', '62.50', '31.42',
       '52.33', '28.75', '28.58', '22.50', '28.50', '37.50', '35.25',
       '18.67', '54.83', '40.92', '19.75', '29.17', '24.58', '33.75',
       '25.42',

In [32]:
data['A3'].unique()

array([ 0.   ,  4.46 ,  0.5  ,  1.54 ,  5.625,  4.   ,  1.04 , 11.585,
        4.915,  0.83 ,  1.835,  6.   ,  6.04 , 10.5  ,  4.415,  0.875,
        5.875,  0.25 ,  8.585, 11.25 ,  1.   ,  8.   , 14.5  ,  6.5  ,
        0.585, 13.   , 18.5  ,  8.5  , 14.79 ,  9.79 ,  7.585,  5.125,
       10.75 ,  1.5  ,  1.585, 11.75 ,  9.415,  9.17 , 15.   ,  1.415,
       13.915, 28.   ,  6.75 ,  2.04 ,  0.665,  2.5  ,  3.   , 11.625,
        4.5  , 12.25 , 16.165,  0.79 ,  0.835,  4.25 ,  0.375, 25.125,
        7.5  ,  5.   ,  7.   ,  5.29 ,  1.165,  9.75 , 19.   ,  3.5  ,
        0.625,  2.21 , 12.75 , 15.5  ,  1.375,  3.54 , 11.   ,  1.75 ,
       16.5  , 12.   ,  2.25 ,  0.75 , 12.5  ,  1.25 ,  1.125,  7.04 ,
       10.335,  6.21 ,  6.665,  9.   ,  5.5  ,  0.54 ,  2.75 ,  9.5  ,
       13.5  ,  3.75 , 16.   ,  0.29 ,  1.665,  7.54 ,  0.46 , 10.   ,
       11.5  ,  3.04 ,  2.   ,  0.08 ,  1.71 ,  3.25 ,  2.54 , 13.585,
        8.665,  9.25 ,  8.17 ,  2.335, 19.5  ,  5.665,  4.625,  0.205,
      

In [33]:
data['A4'].unique()

array(['u', 'y', '?', 'l'], dtype=object)

In [34]:
data['A5'].unique()

array(['g', 'p', '?', 'gg'], dtype=object)

In [35]:
data['A6'].unique()

array(['w', 'q', 'm', 'r', 'cc', 'k', 'c', 'd', 'x', 'i', 'e', 'aa', 'ff',
       'j', '?'], dtype=object)

In [36]:
data['A7'].unique()

array(['v', 'h', 'bb', 'ff', 'j', 'z', '?', 'o', 'dd', 'n'], dtype=object)

In [37]:
data['A8'].unique()

array([ 1.25 ,  3.04 ,  1.5  ,  3.75 ,  1.71 ,  2.5  ,  6.5  ,  0.04 ,
        3.96 ,  3.165,  2.165,  4.335,  1.   ,  5.   ,  0.25 ,  0.96 ,
        3.17 ,  0.665,  0.75 ,  0.835,  7.875,  3.085,  0.5  ,  5.165,
       15.   ,  7.   ,  5.04 ,  7.96 ,  7.585,  0.415,  2.   ,  1.835,
       14.415,  4.5  ,  5.335,  8.625, 28.5  ,  2.625,  0.125,  6.04 ,
        3.5  ,  0.165,  0.875,  1.75 ,  0.   ,  7.415,  0.085,  5.75 ,
        6.   ,  3.   ,  1.585,  4.29 ,  1.54 ,  1.46 ,  1.625, 12.5  ,
       13.5  , 10.75 ,  0.375,  0.585,  0.455,  4.   ,  8.5  ,  9.46 ,
        2.25 , 10.   ,  0.795,  1.375,  1.29 , 11.5  ,  6.29 , 14.   ,
        0.335,  1.21 ,  7.375,  7.5  ,  3.25 , 13.   ,  5.5  ,  4.25 ,
        0.625,  5.085,  2.75 ,  2.375,  8.   ,  1.085,  2.54 ,  4.165,
        1.665, 11.   ,  9.   ,  1.335,  1.415,  1.96 ,  2.585,  5.125,
       15.5  ,  0.71 ,  5.665, 18.   ,  5.25 ,  8.665,  2.29 , 20.   ,
        2.46 , 13.875,  2.085,  4.58 ,  2.71 ,  2.04 ,  0.29 ,  4.75 ,
      

In [38]:
data['A9'].unique()

array(['t', 'f'], dtype=object)

In [39]:
data['A10'].unique()

array(['t', 'f'], dtype=object)

In [40]:
data['A11'].unique()

array([ 1,  6,  0,  5,  7, 10,  3, 17,  2,  9,  8, 15, 11, 12, 40, 23,  4,
       20, 67, 14, 16, 13, 19], dtype=int64)

In [41]:
data['A12'].unique()

array(['f', 't'], dtype=object)

In [42]:
data['A13'].unique()

array(['g', 's', 'p'], dtype=object)

In [43]:
data['A14'].unique()

array(['00202', '00043', '00280', '00100', '00120', '00360', '00164',
       '00080', '00180', '00052', '00128', '00260', '00000', '00320',
       '00396', '00096', '00200', '00300', '00145', '00500', '00168',
       '00434', '00583', '00030', '00240', '00070', '00455', '00311',
       '00216', '00491', '00400', '00239', '00160', '00711', '00250',
       '00520', '00515', '00420', '?', '00980', '00443', '00140', '00094',
       '00368', '00288', '00928', '00188', '00112', '00171', '00268',
       '00167', '00075', '00152', '00176', '00329', '00212', '00410',
       '00274', '00375', '00408', '00350', '00204', '00040', '00181',
       '00399', '00440', '00093', '00060', '00395', '00393', '00021',
       '00029', '00102', '00431', '00370', '00024', '00020', '00129',
       '00510', '00195', '00144', '00380', '00049', '00050', '00381',
       '00150', '00117', '00056', '00211', '00230', '00156', '00022',
       '00228', '00519', '00253', '00487', '00220', '00088', '00073',
       '00121',

In [45]:
data['A15'].unique()

array([     0,    560,    824,      3,  31285,   1349,    314,   1442,
          200,   2690,    245,   1208,   1260,     11,  10000,   5000,
         4000,     35,    713,    551,    500,    300,    221,   2283,
          100,     15,    284,   1236,   5800,    730,    400,  50000,
          456,  15108,   2954,      2,     20,     27,    225,      1,
           38,      5,    130,    147,    210,  11202,   1332,     50,
          258,    567,   1000,   2510,    809,    610,    150,  51100,
          367,    600,    247,    375,    278,    827,   2072,    582,
         2300,   3065,   2200,      6,   1602,   2184,   3376,   2000,
         7544,  10561,    837,  11177,    639,   2028,   1065,    540,
          158,  15000,   3000,   3257,   1655,   1430,      7,    790,
          396,    678,   1187,   6590,    168,   1270,   1210,    742,
         8851,   7059,   1704,    857,   6700,   2503,   9800,    196,
           14,  26726,  18027,     99,    444,   1200,   2010,     13,
      

In [46]:
data['A16'].unique()

array(['+', '-'], dtype=object)

# Replacing character

In [48]:
data = data.replace('?', np.nan)

In [49]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 690 entries, 0 to 689
Data columns (total 16 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   A1      678 non-null    object 
 1   A2      678 non-null    object 
 2   A3      690 non-null    float64
 3   A4      684 non-null    object 
 4   A5      684 non-null    object 
 5   A6      681 non-null    object 
 6   A7      681 non-null    object 
 7   A8      690 non-null    float64
 8   A9      690 non-null    object 
 9   A10     690 non-null    object 
 10  A11     690 non-null    int64  
 11  A12     690 non-null    object 
 12  A13     690 non-null    object 
 13  A14     677 non-null    object 
 14  A15     690 non-null    int64  
 15  A16     690 non-null    object 
dtypes: float64(2), int64(2), object(12)
memory usage: 86.4+ KB


In [50]:
data['A2'] = data['A2'].astype(float)

In [51]:
data['A14'] = data['A14'].astype(float)

In [52]:
data['A16'] = data['A16'].map({'+':1, '-':0})

Add some missing values at random positions in four variables:

In [55]:
random.seed(9001)    # Seed function is used to save the state of a random function
values = set([random.randint(0, len(data)) for p in range(0, 100)])
for var in ['A3', 'A8', 'A9', 'A10']:
 data.loc[values, var] = np.nan

# Removing observations with missing data

In [118]:
df = data

In [120]:
df.isnull().sum()

A1     12
A2     12
A3     92
A4      6
A5      6
A6      9
A7      9
A8     92
A9     92
A10    92
A11     0
A12     0
A13     0
A14    13
A15     0
A16     0
dtype: int64

In [121]:
values = ['A'+str(s) for s in range(1,17)]

In [122]:
df.columns = values

In [141]:
# Let's calculate the percentage of missing values for each variable and sort them in ascending order:

df.isnull().sum().mean().sort_values(ascending=True)

AttributeError: 'float' object has no attribute 'sort_values'

In [124]:
df.isnull().sum()

A1     12
A2     12
A3     92
A4      6
A5      6
A6      9
A7      9
A8     92
A9     92
A10    92
A11     0
A12     0
A13     0
A14    13
A15     0
A16     0
dtype: int64

In [125]:
#  Now, we'll remove the observations with missing data in any of the variables:

df_cca = df.dropna()

In [126]:
# Let's print and compare the size of the original and complete case datasets

print('Number of total observations: {}'.format(len(df)))
print('Number of observations with complete cases:{}'.format(len(df_cca)))
      

Number of total observations: 690
Number of observations with complete cases:564


# Performing mean or median imputation

In [106]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from feature_engine.imputation import MeanMedianImputer

In [143]:
df1 = data

In [144]:
values = ['A'+str(s) for s in range(1,17)]

In [145]:
df1.columns = values

In [146]:
""" In mean and median imputation, the mean or median values should be
calculated using the variables in the train set; therefore, let's separate the data
into train and test sets and their respective targets: """

X_train, X_test, y_train, y_test = train_test_split(
 df1.drop('A16', axis=1), df1['A16'], test_size=0.3,
 random_state=0)

In [147]:
X_train.shape

(483, 15)

In [148]:
y_train.shape

(483,)

In [149]:
# Let's check the percentage of missing values in the train set:

X_train.isnull().mean()

A1     0.008282
A2     0.022774
A3     0.140787
A4     0.008282
A5     0.008282
A6     0.008282
A7     0.008282
A8     0.140787
A9     0.140787
A10    0.140787
A11    0.000000
A12    0.000000
A13    0.000000
A14    0.014493
A15    0.000000
dtype: float64

In [150]:
data.isnull().sum()

A1     12
A2     12
A3     92
A4      6
A5      6
A6      9
A7      9
A8     92
A9     92
A10    92
A11     0
A12     0
A13     0
A14    13
A15     0
A16     0
dtype: int64

In [151]:
# Let's replace the missing values with the median in five numerical variables using pandas:

for var in ['A2', 'A3', 'A8', 'A11', 'A15']:
 value = X_train[var].median()
 X_train[var] = X_train[var].fillna(value)
 X_test[var] = X_test[var].fillna(value)

In [157]:
# To impute missing data with the mean,

value = X_train[var].mean()
value

966.2525879917184

In [158]:
# To do this, let's separate the original dataset into train and test sets, 
# keeping only the numerical variables

X_train, X_test, y_train, y_test = train_test_split(
 data[['A2', 'A3', 'A8', 'A11', 'A15']], data['A16'],
 test_size=0.3, random_state=0)


In [161]:
# Let's create a median imputation transformer using SimpleImputer() from scikit-learn:

imputer = SimpleImputer(strategy='median')

# To perform mean imputation, we should set the strategy to mean:
imputer1 = SimpleImputer(strategy = 'mean')

In [162]:
# Let's fit the SimpleImputer() to the train set so that it learns the median values of the variables:

imputer.fit(X_train)

SimpleImputer(strategy='median')

In [163]:
# Let's inspect the learned median values:

imputer.statistics_


array([28.835,  2.75 ,  1.   ,  0.   ,  6.   ])

In [164]:
# Let's replace missing values with medians:

X_train = imputer.transform(X_train)
X_test = imputer.transform(X_test)

# Implementing mode or frequent category imputation
